version: '3.8'

services:
  tf:
    #image: docker-keras
    build: .
    ports:
      - 8888:8888
    volumes:
      - ../:/tf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
